name: Build Windows EXE on Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests keyring pillow pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --windowed Main.py
          dir dist

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/Main.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
